// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAljupAsTAETfmrZ1-isO5-TWjq536Ctp0',
    appId: '1:292234720259:android:7de624e04ba5d98e280a36',
    messagingSenderId: '292234720259',
    projectId: 'render-app-3c6cd',
    storageBucket: 'render-app-3c6cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJQBaMQNbrkZ9ff2A2taOhfeNRJgFu2Y',
    appId: '1:292234720259:ios:6a49e83bfb7017e6280a36',
    messagingSenderId: '292234720259',
    projectId: 'render-app-3c6cd',
    storageBucket: 'render-app-3c6cd.appspot.com',
    androidClientId: '292234720259-qp1kslfav28ikcvuang9a81n4oo3do14.apps.googleusercontent.com',
    iosClientId: '292234720259-m6bvfvesu7koilobcd3hj6t3dlr1p8ii.apps.googleusercontent.com',
    iosBundleId: 'com.project9.render',
  );
}
